- name: Examples of cisco.ise.network_device[_info]
  hosts: ise_deployment
  vars_files:
    - credentials.yaml
  gather_facts: no
  tasks:



  # - name: Get a network policy set by id
  #   cisco.ise.network_access_policy_set_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     id: "acd4b55d-dca3-4b93-a160-8a2d01669827"
  #   register: result

  # - name: Print by id
  #   ansible.builtin.debug:
  #     var: result

   - name: Create a New Policy Set
     cisco.ise.network_access_policy_set:
       ise_hostname: "{{ise_hostname}}"
       ise_username: "{{ise_username}}"
       ise_password: "{{ise_password}}"
       ise_verify: "{{ise_verify}}"
       state: present
       condition:
        attributeName: Device IP Address
        attributeValue: "10.101.10.10"
        conditionType: "ConditionAttributes"
        dictionaryName: "Network Access"
        isNegate: false
        operator: "ipEquals"
        default: false
       description: "Policy Created through Ansible"
       id: 7bca72c0-712e-41ea-9d58-a8c368bc234d
       isProxy: false
       name: TestPolicy
       rank: 0
       serviceName: "Default Network Access"
       state: present
     register: result

   - name: Get all network policy set
     cisco.ise.network_access_policy_set_info:
       ise_hostname: "{{ise_hostname}}"
       ise_username: "{{ise_username}}"
       ise_password: "{{ise_password}}"
       ise_verify: "{{ise_verify}}"
     register: result

   - name: Print all
     ansible.builtin.debug:
       var: result

  # - name: Delete a network policy set by id
  #   cisco.ise.network_access_policy_set:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     state: absent
  #     id: 4f83e8c4-978e-4767-a218-9d5472d4dcc7
  #   register: result